[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "PartyManagementSystem"
dynamic = ["version"]

[tool.setuptools_scm]
# Записываем версию в файл при любой сборке
version_file = "config/_version.py"

[tool.setuptools.packages.find]
# Включаем папку config.
include = ["config", "config.*", "app_*"]
# Исключаем статику, шаблоны, медиа и виртуальное окружение
exclude = ["static*", "templates*", "media*", ".venv*", "venv*"]