"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Импорты встроенных библиотек.
from pathlib import Path
import os
import random
import string

# Импорты сторонних библиотек.
from dotenv import load_dotenv
import psycopg

try:
    from ._version import version as SERVICE_VERSION
except ImportError:
    SERVICE_VERSION = '0.0.0-dev'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Импорт переменных.
dotenv_path = os.path.join(os.path.dirname(__file__), '.env')
if os.path.exists(dotenv_path):
    load_dotenv(dotenv_path=dotenv_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (
    True if os.getenv('DEBUG') == '1'
    else False
)
SERVICE_MODE_TEXT = (
    'DEBUG (Разработка)'
    if DEBUG
    else 'PRODUCTION (Производство)'
)
SERVICE_MODE_COLOR = (
    '#FABB1C'
    if DEBUG
    else '#BBCF32'
)

if os.environ.get('PROCESS_TYPE') == 'web':
    print(f'Запущена версия {SERVICE_VERSION} в режиме {SERVICE_MODE_TEXT}')

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://127.0.0.1',
    'http://*',
    'https://*'
]
CORS_ORIGIN_WHITELIST = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tasks',
    'django_tasks_db',
    'rest_framework',
    'drf_spectacular',
    'app_uip.apps.AppUipConfig',
    'app_wms.apps.AppWmsConfig',
    'app_cz.apps.AppCzConfig',
    'app_factory.apps.AppFactoryConfig',
    'app_helper.apps.AppHelperConfig',
    'app_page.apps.AppPageConfig',
    'app_scheduler.apps.AppSchedulerConfig',
    'app_event.apps.AppEventConfig',

]

# Настройки DRF.
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Конфигурация задач.
TASKS = {
    'default': {
        "BACKEND": "django_tasks_db.DatabaseBackend",
        "QUEUES": ["default", "emails", "high-priority"],
    }
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Система управления партиями API',
    'DESCRIPTION': 'API для работы с кодами маркировки и УИП',
    'VERSION': SERVICE_VERSION,
    'SERVE_INCLUDE_SCHEMA': False,
    # Явные имена enum-компонентов, чтобы избежать коллизий имён
    # (несколько наборов выборок с одинаковым именем поля, например «status»).
    'ENUM_NAME_OVERRIDES': {
        'UIPStatusEnum': 'app_uip.models.PartyStatusChoices',
        'ProductionPartyStatusEnum': 'app_uip.models.ProductionPartyStatusChoices',
        'ProductionPartySyncStatusEnum': 'app_uip.models.ProductionPartySyncStatusChoices',
        'CISCodesCzStatusEnum': 'app_cz.models.CISCodesStatusChoices',
        'ProductionCodeStatusEnum': 'app_cz.models.ProductionCodeStatusChoices',
        'PackagingLevelEnum': 'app_factory.models.PackagingLevelChoices',
        'TypeFormationUIPEnum': 'app_factory.models.TypeFormationUIP',
        'TypeProductEnum': 'app_cz.enums.TypeProduct',
    },
    'TAGS': [
        {
            'name': 'Честный Знак',
            'description': 'Методы для взаимодействия с системой маркировки «Честный Знак» (резервирование, синхронизация, работа с СУЗ)'
        },
        {
            'name': 'Производство',
            'description': 'Методы для взаимодействия с производством (справочники)'
        },
        {
            'name': 'УИП',
            'description': 'Методы для проверки и получения списков Уникальных Идентификаторов Партий'
        }
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app_helper.middleware.LoadTrackingMiddleware'
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        # FIXME Настроить Redis:
        # 'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        # 'LOCATION': 'redis://127.0.0.1:6379/1',
    }
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'config.context_processors.service_context',
                'config.context_processors.user_context',
                'config.context_processors.global_footer_info',
                'config.context_processors.service_status_info'
            ],
        },
    },
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': 'postgres',
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = os.getenv('TIME_ZONE') or 'Europe/Moscow'

USE_I18N = True

USE_TZ = (
    True if os.getenv('IS_TIME_ZONE') == '1'
    else False
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Статика
STATIC_URL = 'static/'
# Разработка.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
]
# Прод.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')

# Медиа.
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# ==========================================
# Почта (уведомления).
# ==========================================
# По умолчанию — консольный бэкенд (в разработке письма выводятся в консоль).
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', '1') == '1'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@localhost')

# ==========================================
# Мониторинг резерва УИП.
# ==========================================
# Лимит зарезервированных УИП (установлен системой «Честный Знак»).
UIP_RESERVE_LIMIT = int(os.getenv('UIP_RESERVE_LIMIT', '10000'))
# Получатели уведомлений о состоянии резерва УИП (через запятую).
UIP_RESERVE_NOTIFICATION_EMAILS = [
    email.strip()
    for email in os.getenv('UIP_RESERVE_NOTIFICATION_EMAILS', '').split(',')
    if email.strip()
]

# ==========================================
# Проверка доступности внешних сервисов.
# ==========================================
# Адрес сервиса 1С (например, http://192.168.1.10:8080) для проверки на странице статусов.
ONEC_URL = os.getenv('ONEC_URL', '')

# ==========================================
# Лимиты запросов.
# ==========================================
# Лимит количества GET/POST-параметров в одном запросе. Увеличен для
# массовых операций в админке (например, удаление всех товаров Национального
# каталога передаёт по одному полю на каждую выбранную строку).
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(os.getenv('DATA_UPLOAD_MAX_NUMBER_FIELDS', '5000'))

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Генерируем имя сессии, если он не указан в файле .env.
letters = string.ascii_lowercase
random_session_cookie_name = "".join(random.choices(letters, k=10))

# Наименование сессии для работы разных проектов на одном сервере.
SESSION_COOKIE_NAME = os.getenv('SESSION_COOKIE_NAME', random_session_cookie_name)
